In [9]:
import numpy as np
a=np.arange(1,101)
a1=np.array(a)
print(np.ndim(a1))#Dimensions
print(np.shape(a1))#shape
print(a1) #1-D
r1=a1.reshape(2,50)
print(np.ndim(r1))#Dimensions
print(np.shape(r1))#shape
print(r1) #2-D
r2=a1.reshape(2,5,10)#reshaping
print(np.ndim(r2))#Dimensions
print(np.shape(r2))#shape
print(r2) #3-D
print(r2[1,0:,0])#Indexing and slicing


1
(100,)
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
2
(2, 50)
[[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
   19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
   37  38  39  40  41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68
   69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86
   87  88  89  90  91  92  93  94  95  96  97  98  99 100]]
3
(2, 5, 10)
[[[  1   2   3   4   5   6   7   8   9  10]
  [ 11  12  13  14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27  28  29  30]
  [ 31  32  33

In [18]:
l1=[[1,2,6],[9,6,4],[7,0,3]]
ar1=np.array(l1)
print(ar1)
s1=np.sort(ar1,axis=1)#sorting elements row wise
print(s1)
s2=np.sort(ar1,axis=0)#sorting elements column wise
print(s2)
w1=np.where(ar1%2==0) #finding element using where
print(w1)
as1=np.array_split(ar1,2)#spliting array into number of pieces
print(as1)

[[1 2 6]
 [9 6 4]
 [7 0 3]]
[[1 2 6]
 [4 6 9]
 [0 3 7]]
[[1 0 3]
 [7 2 4]
 [9 6 6]]
(array([0, 0, 1, 1, 2], dtype=int64), array([1, 2, 1, 2, 1], dtype=int64))
[array([[1, 2, 6],
       [9, 6, 4]]), array([[7, 0, 3]])]
